### ISSUE TITLE
domain able to receive email (delivery using MX, A, AAAA)

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster#309]
From Future tests in the Test Requirements:

 * domain able to receive email (delivery using MX, A, AAAA)
 * test if mail delivery possible

**Comment by cdybedahl** [comment]
Um. These are tests we removed from DNSCheck because they're impossible to implement. I suspect they're even impossible to _define_ usefully.

**Comment by pawal** [comment]
I know. But others argued to keep them as future tests in Zonemaster, which is why the e-mail tests were kept as future tests. This might still be up for discussion though.

**Comment by patrikhson** [comment]
> On 30 jan 2015, at 10:06, Patrik Wallström <notifications@github.com> wrote:
> 
> I know. But others argued to keep them as future tests in Zonemaster, which is why the e-mail tests were kept as future tests. This might still be up for discussion though.
> 
Tests have been requested due to two reasons:

- Some parties think email address in SOA should work
- Some parties think email to the domain itself should work

"Should work" have been defined as:

1. Look up MX
2. Look up A/AAAA
3. Open SMTP to port 25 to target
4. Do SMTP commands HELO, MAIL FROM and RCPT TO followed by a QUIT, with 3xx (and 4xx for RCPT TO) responses acceptable

I do not see that be impossible to implement (as I did that in one of the DNSCHECK implementations myself), and I think it is a feature that people will ask for. Configurable to be turned off.

   paf

**Comment by cdybedahl** [comment]
That is indeed the exact implementation we removed from DNSCheck for being useless. It tells you absolutely nothing about if the mail was ever put in some kind of mailbox, much less if it will ever be seen by human eyes. It's also a very efficient way of getting your server's IP address blacklisted for spamming.

Zonemaster is plugin-based. Anyone who really wants this test can easily implement a module of their own that does it. My opinion remains that if it needs another protocol than DNS, it's out of scope for the base set of tests.

**Comment by sandoche2k** [comment]
@patrikhson Explanation provided above. Won't fix as part of the Zonemaster  project.
