### ISSUE TITLE
Uniform pattern while naming directories and files 

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster#350]
In different components the files and directories are named in different manners. 

For example "Doc" in one component and "doc" in another component

ASNLookup.pm in one and create_db_couchdb.pl in another.

Can we decide on a uniform policy and if needed we can document it.

**Comment by cdybedahl** [comment]
`.pm` files need to follow the rules for naming Perl modules. `.pl` files are Unix script files, which are usually all in lower case. Some directories are named according to Perl module conventions, like `lib`, `t` and `share`. As for others, I can see points both for having them all-lowercase in order to be consistent and for having them with an initial capital to mark them as ours rather than standard.

**Comment by sandoche2k** [comment]
@pawal - close this issue here
