### ISSUE TITLE
Imperfect error message when there is a full lame delegation

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#370]
google.my does exist:

```
% dig @dns.mynic.net.my. NS google.my

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> @dns.mynic.net.my. NS google.my
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63631
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 6, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;google.my.		IN NS

;; AUTHORITY SECTION:
google.my.		86400 IN NS ns2.google.com.
google.my.		86400 IN NS ns1.google.com.
...
```

But Zonemaster-Web pops up "Domain does not exist". Actually, it is a lame delegation and should be diagnosed as such:

```
% dig @ns2.google.com. A google.my   

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> @ns2.google.com. A google.my
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 16647
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;google.my.		IN A

;; Query time: 17 msec
;; SERVER: 216.239.34.10#53(216.239.34.10)
;; WHEN: Wed Apr 15 15:10:36 CEST 2015
;; MSG SIZE  rcvd: 27

```

**Comment by sandoche2k** [comment]
@pawal assign it to 2015.2, assign it to VLE
@VLE i need the resource required to finish this task and proposed dates of completion

**Comment by cdybedahl** [comment]
This is not a problem in the code, as such, but a problem with the specifications. What's happening here is that "preflight" heuristic, which is intended to be fast rather than correct, wrongly considers the domain name to be untestable and balks. This is a straight port of a functionality in DNSCheck that I have long considered dubious even there. The intent of that test is to catch end users doing things like entering email addresses as the domain to be tested, and in those cases fail fast without polluting the database with useless names.

At the moment, it is not (as far as I know) defined exactly what the "preflight" test should do (as in what it should be testing). My suggestion is that the specifications for the web GUI be amended to state that the preflight test should consist of executing the Engine tests basic00, syntax01 and syntax02 on the name from the user, and if they fail reject the test request immediately. If they pass, the name should be handed over to the test engine for proper evaluation. That way, they would still be very fast (none of those three tests make any DNS queries) and catch things like email addresses (syntax01 will balk at the at-sign). When the specification is changed, the code in `Zonemaster::WebBackend::Engine::validate_syntax()` should be adjusted to implement the specification as written.

**Comment by einar** [comment]
It's not a straight port of DNSCheck's preflight because then it would work better. The current preflight in Zonemaster cannot handle SERVFAIL which rules out a LOT of domains.

However I do agree that your solution is the best one; if we cant get that or similar we should remove it completely until we can make it useable.

**Comment by sandoche2k** [comment]
@bortzmeyer please guide us here for the appropriate way for the preflight check. 

Stephane’s method 
——————————-
If NXDOMAIN
	Domain does not exist
Exit
If NOERROR || ANSWER == 0 
	Domain exists, but is not a zone
Exit
Feed the input to the engine for evaluation

What we get from the Web UI on testing 21.se “Unknown error while checking for domain existence”
  
Calle’s method
————————
If (Test Basic00 (check whether it is a valid domain)) 
	Invalid domain
Exit
If (Test Syntax 01 (Illegal characters) || Syntax 02 (hyphen) )
	Invalid domain
Exit
Feed the input to the engine for evaluation

What i see as advantage from Calle’s method is that the preflight check is limited to syntactical/semantical characteristics of the input i.e. the domain name. For any other tests, it is the engine which is assigned the task. Thus for 21.se, the results could be : there are no name server found at the child and for “gouv.fr” there is no delegation found at parent. On the contrary, currently in ZM, the response for 21.se is ““Unknown error while checking for domain existence” and for gouv.fr “Domain exists, but is not a zone”.

**Comment by cdybedahl** [comment]
(There is a pull request for my variant now.)

Deciding which variant you want to use would probably be easier if there was a clear high-level statement expressing what the preflight test is supposed to achieve. With my variant it is only "make sure that the input is a syntactically valid domain name". The various variants that rely on sending DNS queries and evaluating the responses all have some degree of "make sure that the zone given exists". I believe that any such test will always be problematic, since "exists" when it comes to DNS zones is a surprisingly slippery concept.

**Comment by patrikhson** [comment]
On 5 Jun 2015, at 10:04, sandoche2k wrote:

> Calle’s method
> ————————
> If (Test Basic00 (check whether it is a valid domain)) 
> Invalid domain
> Exit
> If (Test Syntax 01 (Illegal characters) || Syntax 02 (hyphen) )
> Invalid domain
> Exit
> Feed the input to the engine for evaluation

It is important that one can with configuration/arguments bypass also the preflight tests just like other tests. For example syntax checking as it might very well be the case that zonemaster is run on delegations that do not fulfil whatever policy a parent zone owner might have. I.e. it is my view that a testing tool should not "give up" for any kind of policy violation. Instead just continue to chew through the data and, if requested, report on the policy violation.

So, the more pre flight tests are included from a configuration point of view as other tests, I think the design is correct.

How it is integrated in the tool itself, I trust you all on making the correct decision! :-)

   Patrik

**Comment by cdybedahl** [comment]
The "preflight" test is exclusively a function of the end-user web interface included in the full Zonemaster distribution. It does not in any way affect the function of the test engine, the CLI or tools written by third parties (unless those tools make a specific effort to use it).

**Comment by mtoma** [comment]
Just one important precision here. The preflight test for the "domain check" and "Pre-delegated domain check" tabs are different. The online DNS checks are done only for the "domain check" tab.
For example 21.se can't be tested through the "domain check" tab but can be tested through the "Pre-delegated domain check" tab.

**Comment by cdybedahl** [comment]
Preflight test has been changed to be more permissive in what it passes on to the test engine.
