### ISSUE TITLE
Raw perl variable data printed in "Connectivity section report"

### ISSUE THREAD

**Issue by igit** [dotse/zonemaster#419]
Checking this domain (univ-lorraine.fr) https://zonemaster.fr/test/39209, I've a strange output in connectivity section which prints raw perl variable data (see attached screenshot).

![screen shot 2015-10-14 at 11 01 31](https://cloud.githubusercontent.com/assets/514465/10480919/77f6cf5a-726d-11e5-9330-7fa68268046d.png)

**Comment by pawal** [comment]
Thank you for the report. This error is only occurring in the web interface. @mtoma, what is the status of fixing this?

**Comment by mtoma** [comment]
This id described in https://github.com/dotse/zonemaster-backend/issues/127
The required steps for this are:
1. Add a travis test to test this issue
2. Fix the issue (as described in issue https://github.com/dotse/zonemaster-backend/issues/127)
3. Decide when to release into production (right now the website and backend are about 6 months behind the git head because we need some formal testing  and validation)

**Comment by sandoche2k** [comment]
@mtoma I think the points 1 and 2 above, you will be doing..

For the 3rd point, myselves and @einar  will have a look at it.

**Comment by sandoche2k** [comment]
@igit  fixed https://zonemaster.net/test/10fb407d53741217
