### ISSUE TITLE
System Error when IPv6 advanced option selected

### ISSUE THREAD

**Issue by jpierre03** [dotse/zonemaster#429]
While trying an IPv6 only check, an error was raised : 

~~~~
Erreur fatale dans le module Zonemaster::Test::Connectivity:
Can't use an undefined value as an ARRAY reference at 
../zonemaster-engine/lib/Zonemaster/Test/Connectivity.pm line 269. 
~~~

Reference to zonecheck test : https://zonemaster.net/test/29fdd49b2b102b8e

**Comment by sandoche2k** [comment]
The issue has been fixed in the engine. You can verify by making a
pull request of the engine (https://github.com/dotse/zonemaster-engine)
and testing from the CLI (https://github.com/dotse/zonemaster-cli).

zonemaster-cli --no-ipv4 cafax.se
Seconds Level     Message
======= ========= =======
Looks OK.


Its true that the modification made in the engine is still not visible
in the GUI (https://zonemaster.net/test/461612e431176f41), since the GUI
has to be updated with the latest release of the engine. It will be done
during the next release of the GUI.
