### ISSUE TITLE
ZoneMaster is too fast to claim a NS is a recursor

### ISSUE THREAD

**Issue by bortzmeyer** [dotse/zonemaster#433]
When testing stratcom.mil (https://zonemaster.net/test/7cf248ca34350e96) ZoneMaster says "Nameserver kingfisher1.stratcom.mil/143.250.3.75 is a recursor. Nameserver kingfisher2.stratcom.mil/143.250.4.75 is a recursor." These to name servers do reply with RD (bad) but they are not really recursors, they reply NXDOMAIN to all out-of-bailiwick queries:

%  dig @143.250.4.75 ANY fr          

; <<>> DiG 9.9.5-12-Debian <<>> @143.250.4.75 ANY fr
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 31719
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;fr.			IN ANY

;; AUTHORITY SECTION:
.			86400 IN SOA A.ROOT-SERVERS.NET. NSTLD.VERISIGN-GRS.COM. (
				2015112401 ; serial
				1800       ; refresh (30 minutes)
				900        ; retry (15 minutes)
				604800     ; expire (1 week)
				86400      ; minimum (1 day)
				)

;; Query time: 232 msec
;; SERVER: 143.250.4.75#53(143.250.4.75)
;; WHEN: Sun Nov 29 18:48:56 CET 2015
;; MSG SIZE  rcvd: 106

**Comment by sandoche2k** [comment]
The error has been fixed in the latest engine version (1.0.10). The GUI
will be runninb on this version  by 15th december

zonemaster-cli  stratcom.mil
Seconds Level     Message
======= ========= =======
   7.05 WARNING   All nameservers have IPv4 addresses in the same AS
(27064).
   7.05 WARNING   All nameservers are in the same AS (27064).
   7.50 NOTICE    The number of NSEC3 iterations is 150, which is on the
high side.
  16.46 NOTICE    SOA 'refresh' value (10800) is less than the recommended
minimum (14400).

**Comment by sandoche2k** [comment]
And you can see the result in the GUI test environement

http://zonemaster.rd.nic.fr:5080/test/b4f1ca3a9619f90f
